# Checking the version of pytorch installed

In [ ]:
import torch
# Print out the version of pytorch
torch.__version__

'2.10.0+cpu'

## Creating a tensor from a scalar

In [4]:
scalar = torch.tensor(7)
# Print out the tensor
scalar
# Check the dimensions of our scalar
scalar.ndim
# Get the Python number from the tensor
scalar.item()

7

## Creating a tensor from a vector

In [16]:
# A vector is a single dimension tensor
vector = torch.tensor([7, 7])
vector
# Check the number of dimensions of the vector
vector.ndim
# Get the python list from the vector tensor
vector.tolist()
# Check shape of vector
vector.shape

torch.Size([2])

## Creating a tensor from a matrix

In [ ]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
MATRIX
# Check the number of dimensions of the matrix
MATRIX.ndim
# Get the shape of the matrix
MATRIX.shape

torch.Size([3, 3])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6],[7,8,9]]])
TENSOR
# Check the number of dimensions of the tensor
TENSOR.ndim
# Get the shape of the tensor
TENSOR.shape

torch.Size([1, 3, 3])

### In practise, scalars and vectors are represented with lowercase letters. Tensors and matrices are represented with uppercase letters.

## Creating a random tensor

In [22]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor

# create a random tensor of size (224, 224, 3)
random_image_tensor = torch.rand(size=(224, 224, 3))
# random_image_tensor
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.ndim, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2,
 torch.Size([3, 4]))

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [25]:
# Creating a tensor of range 10
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Creating a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Getting information from tensors

In [27]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.9494, 0.0512, 0.5490, 0.6735],
        [0.2955, 0.2436, 0.7649, 0.8296],
        [0.4336, 0.2107, 0.9238, 0.7751]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


### Matrix multiplication

In [28]:
# Use torch.matmul() method for matrix multiplication
# Inner dimensions must work (2,3)*(3,2)
# Resulting matrix has the shape of the outer dimensions (2,3)*(3,2) =(2,2)
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [30]:
# Element wise multiplication
tensor * tensor
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [33]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Indexing a tensor

In [34]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [35]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [38]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 0]

tensor([[1, 4, 7]])

In [39]:
# Converting between numpy and tensors
# torch.from_numpy(ndarray): numpy to tensor
# torch.Torch.numpy(): tensot to numpy
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))